CREATE TABLE t_order_detail (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    price INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    INDEX (id),
    PRIMARY KEY (id)
);

ALTER TABLE t_order_detail
ADD CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES t_order(id),
ADD CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES m_item(id);